// autogenerated by rzubr
//case  0: // start: toml
//case  1: // toml: statements sections
//case  2: // toml: statements
//case  3: // toml: sections
//case  4: // toml: 
//case  5: // sections: sections "[" keypath "]" ENDLINE statements
//case  6: // sections: sections "[" keypath "]" ENDLINE
//case  7: // sections: sections "[" "[" keypath "]" "]" ENDLINE statements
//case  8: // sections: sections "[" "[" keypath "]" "]" ENDLINE
//case  9: // sections: "[" keypath "]" ENDLINE statements
//case 10: // sections: "[" keypath "]" ENDLINE
//case 11: // sections: "[" "[" keypath "]" "]" ENDLINE statements
//case 12: // sections: "[" "[" keypath "]" "]" ENDLINE
//case 13: // keypath: keypath "." key
//case 14: // keypath: key
//case 15: // key: BAREKEY
//case 16: // key: STRKEY
//case 17: // statements: statements pair ENDLINE
//case 18: // statements: pair ENDLINE
//case 19: // value: BOOLEAN
//case 20: // value: FIXNUM
//case 21: // value: FLONUM
//case 22: // value: DATETIME
//case 23: // value: STRING
//case 24: // value: STRKEY
//case 25: // value: "[" array "]"
//case 26: // value: "{" table "}"
//case 27: // array: endln
//case 28: // array: value_list
//case 29: // array: value_list "," endln
//case 30: // value_list: endln value endln
//case 31: // value_list: value_list "," endln value endln
//case 32: // endln: 
//case 33: // endln: ENDLINE
//case 34: // table: 
//case 35: // table: pair_list
//case 36: // table: pair_list ","
//case 37: // pair_list: pair
//case 38: // pair_list: pair_list "," pair
//case 39: // pair: key "=" value

    void
    define_state ()
    {
        enum { start = 17, toml, sections, keypath, key, statements, value,
            array, value_list, endln, table, pair_list, pair };

        to (1, TOKEN_ENDMARK, 250);
        to (1, TOKEN_LBRACKET, 6);
        to (1, TOKEN_BAREKEY, 8);
        to (1, TOKEN_STRKEY, 9);
        to (1, toml, 2);
        to (1, statements, 3);
        to (1, sections, 4);
        to (1, pair, 5);
        to (1, key, 7);

        to (2, TOKEN_ENDMARK, 255);

        to (3, TOKEN_ENDMARK, 252);
        to (3, TOKEN_LBRACKET, 6);
        to (3, TOKEN_BAREKEY, 8);
        to (3, TOKEN_STRKEY, 9);
        to (3, sections, 10);
        to (3, pair, 11);
        to (3, key, 7);

        to (4, TOKEN_ENDMARK, 251);
        to (4, TOKEN_LBRACKET, 12);

        to (5, TOKEN_ENDLINE, 13);

        to (6, TOKEN_LBRACKET, 15);
        to (6, TOKEN_BAREKEY, 8);
        to (6, TOKEN_STRKEY, 9);
        to (6, keypath, 14);
        to (6, key, 16);

        to (7, TOKEN_EQUAL, 17);

        to (8, TOKEN_EQUAL, 239);
        to (8, TOKEN_RBRACKET, 239);
        to (8, TOKEN_DOT, 239);

        to (9, TOKEN_EQUAL, 238);
        to (9, TOKEN_RBRACKET, 238);
        to (9, TOKEN_DOT, 238);

        to (10, TOKEN_ENDMARK, 253);
        to (10, TOKEN_LBRACKET, 12);

        to (11, TOKEN_ENDLINE, 18);

        to (12, TOKEN_LBRACKET, 20);
        to (12, TOKEN_BAREKEY, 8);
        to (12, TOKEN_STRKEY, 9);
        to (12, keypath, 19);
        to (12, key, 16);

        to (13, TOKEN_LBRACKET, 236);
        to (13, TOKEN_BAREKEY, 236);
        to (13, TOKEN_STRKEY, 236);
        to (13, TOKEN_ENDMARK, 236);

        to (14, TOKEN_RBRACKET, 21);
        to (14, TOKEN_DOT, 22);

        to (15, TOKEN_BAREKEY, 8);
        to (15, TOKEN_STRKEY, 9);
        to (15, keypath, 23);
        to (15, key, 16);

        to (16, TOKEN_RBRACKET, 240);
        to (16, TOKEN_DOT, 240);

        to (17, TOKEN_BOOLEAN, 25);
        to (17, TOKEN_FIXNUM, 26);
        to (17, TOKEN_FLONUM, 27);
        to (17, TOKEN_DATETIME, 28);
        to (17, TOKEN_STRING, 29);
        to (17, TOKEN_STRKEY, 30);
        to (17, TOKEN_LBRACKET, 31);
        to (17, TOKEN_LBRACE, 32);
        to (17, value, 24);

        to (18, TOKEN_LBRACKET, 237);
        to (18, TOKEN_BAREKEY, 237);
        to (18, TOKEN_STRKEY, 237);
        to (18, TOKEN_ENDMARK, 237);

        to (19, TOKEN_RBRACKET, 33);
        to (19, TOKEN_DOT, 22);

        to (20, TOKEN_BAREKEY, 8);
        to (20, TOKEN_STRKEY, 9);
        to (20, keypath, 34);
        to (20, key, 16);

        to (21, TOKEN_ENDLINE, 35);

        to (22, TOKEN_BAREKEY, 8);
        to (22, TOKEN_STRKEY, 9);
        to (22, key, 36);

        to (23, TOKEN_RBRACKET, 37);
        to (23, TOKEN_DOT, 22);

        to (24, TOKEN_ENDLINE, 215);
        to (24, TOKEN_COMMA, 215);
        to (24, TOKEN_RBRACE, 215);

        to (25, TOKEN_ENDLINE, 235);
        to (25, TOKEN_COMMA, 235);
        to (25, TOKEN_RBRACE, 235);
        to (25, TOKEN_RBRACKET, 235);

        to (26, TOKEN_ENDLINE, 234);
        to (26, TOKEN_COMMA, 234);
        to (26, TOKEN_RBRACE, 234);
        to (26, TOKEN_RBRACKET, 234);

        to (27, TOKEN_ENDLINE, 233);
        to (27, TOKEN_COMMA, 233);
        to (27, TOKEN_RBRACE, 233);
        to (27, TOKEN_RBRACKET, 233);

        to (28, TOKEN_ENDLINE, 232);
        to (28, TOKEN_COMMA, 232);
        to (28, TOKEN_RBRACE, 232);
        to (28, TOKEN_RBRACKET, 232);

        to (29, TOKEN_ENDLINE, 231);
        to (29, TOKEN_COMMA, 231);
        to (29, TOKEN_RBRACE, 231);
        to (29, TOKEN_RBRACKET, 231);

        to (30, TOKEN_ENDLINE, 230);
        to (30, TOKEN_COMMA, 230);
        to (30, TOKEN_RBRACE, 230);
        to (30, TOKEN_RBRACKET, 230);

        to (31, TOKEN_BOOLEAN, 222);
        to (31, TOKEN_FIXNUM, 222);
        to (31, TOKEN_FLONUM, 222);
        to (31, TOKEN_DATETIME, 222);
        to (31, TOKEN_STRING, 222);
        to (31, TOKEN_STRKEY, 222);
        to (31, TOKEN_LBRACKET, 222);
        to (31, TOKEN_LBRACE, 222);
        to (31, TOKEN_RBRACKET, 222);
        to (31, TOKEN_ENDLINE, 41);
        to (31, array, 38);
        to (31, endln, 39);
        to (31, value_list, 40);

        to (32, TOKEN_RBRACE, 220);
        to (32, TOKEN_BAREKEY, 8);
        to (32, TOKEN_STRKEY, 9);
        to (32, table, 42);
        to (32, pair_list, 43);
        to (32, pair, 44);
        to (32, key, 7);

        to (33, TOKEN_ENDLINE, 45);

        to (34, TOKEN_RBRACKET, 46);
        to (34, TOKEN_DOT, 22);

        to (35, TOKEN_LBRACKET, 244);
        to (35, TOKEN_ENDMARK, 244);
        to (35, TOKEN_BAREKEY, 8);
        to (35, TOKEN_STRKEY, 9);
        to (35, statements, 47);
        to (35, pair, 5);
        to (35, key, 7);

        to (36, TOKEN_RBRACKET, 241);
        to (36, TOKEN_DOT, 241);

        to (37, TOKEN_RBRACKET, 48);

        to (38, TOKEN_RBRACKET, 49);

        to (39, TOKEN_RBRACKET, 227);
        to (39, TOKEN_BOOLEAN, 25);
        to (39, TOKEN_FIXNUM, 26);
        to (39, TOKEN_FLONUM, 27);
        to (39, TOKEN_DATETIME, 28);
        to (39, TOKEN_STRING, 29);
        to (39, TOKEN_STRKEY, 30);
        to (39, TOKEN_LBRACKET, 31);
        to (39, TOKEN_LBRACE, 32);
        to (39, value, 50);

        to (40, TOKEN_RBRACKET, 226);
        to (40, TOKEN_COMMA, 51);

        to (41, TOKEN_BOOLEAN, 221);
        to (41, TOKEN_FIXNUM, 221);
        to (41, TOKEN_FLONUM, 221);
        to (41, TOKEN_DATETIME, 221);
        to (41, TOKEN_STRING, 221);
        to (41, TOKEN_STRKEY, 221);
        to (41, TOKEN_LBRACKET, 221);
        to (41, TOKEN_LBRACE, 221);
        to (41, TOKEN_RBRACKET, 221);
        to (41, TOKEN_COMMA, 221);

        to (42, TOKEN_RBRACE, 52);

        to (43, TOKEN_RBRACE, 219);
        to (43, TOKEN_COMMA, 53);

        to (44, TOKEN_COMMA, 217);
        to (44, TOKEN_RBRACE, 217);

        to (45, TOKEN_LBRACKET, 248);
        to (45, TOKEN_ENDMARK, 248);
        to (45, TOKEN_BAREKEY, 8);
        to (45, TOKEN_STRKEY, 9);
        to (45, statements, 54);
        to (45, pair, 5);
        to (45, key, 7);

        to (46, TOKEN_RBRACKET, 55);

        to (47, TOKEN_LBRACKET, 245);
        to (47, TOKEN_ENDMARK, 245);
        to (47, TOKEN_BAREKEY, 8);
        to (47, TOKEN_STRKEY, 9);
        to (47, pair, 11);
        to (47, key, 7);

        to (48, TOKEN_ENDLINE, 56);

        to (49, TOKEN_ENDLINE, 229);
        to (49, TOKEN_COMMA, 229);
        to (49, TOKEN_RBRACE, 229);
        to (49, TOKEN_RBRACKET, 229);

        to (50, TOKEN_COMMA, 222);
        to (50, TOKEN_RBRACKET, 222);
        to (50, TOKEN_ENDLINE, 41);
        to (50, endln, 57);

        to (51, TOKEN_BOOLEAN, 222);
        to (51, TOKEN_FIXNUM, 222);
        to (51, TOKEN_FLONUM, 222);
        to (51, TOKEN_DATETIME, 222);
        to (51, TOKEN_STRING, 222);
        to (51, TOKEN_STRKEY, 222);
        to (51, TOKEN_LBRACKET, 222);
        to (51, TOKEN_LBRACE, 222);
        to (51, TOKEN_RBRACKET, 222);
        to (51, TOKEN_ENDLINE, 41);
        to (51, endln, 58);

        to (52, TOKEN_ENDLINE, 228);
        to (52, TOKEN_COMMA, 228);
        to (52, TOKEN_RBRACE, 228);
        to (52, TOKEN_RBRACKET, 228);

        to (53, TOKEN_RBRACE, 218);
        to (53, TOKEN_BAREKEY, 8);
        to (53, TOKEN_STRKEY, 9);
        to (53, pair, 59);
        to (53, key, 7);

        to (54, TOKEN_LBRACKET, 249);
        to (54, TOKEN_ENDMARK, 249);
        to (54, TOKEN_BAREKEY, 8);
        to (54, TOKEN_STRKEY, 9);
        to (54, pair, 11);
        to (54, key, 7);

        to (55, TOKEN_ENDLINE, 60);

        to (56, TOKEN_LBRACKET, 242);
        to (56, TOKEN_ENDMARK, 242);
        to (56, TOKEN_BAREKEY, 8);
        to (56, TOKEN_STRKEY, 9);
        to (56, statements, 61);
        to (56, pair, 5);
        to (56, key, 7);

        to (57, TOKEN_COMMA, 224);
        to (57, TOKEN_RBRACKET, 224);

        to (58, TOKEN_RBRACKET, 225);
        to (58, TOKEN_BOOLEAN, 25);
        to (58, TOKEN_FIXNUM, 26);
        to (58, TOKEN_FLONUM, 27);
        to (58, TOKEN_DATETIME, 28);
        to (58, TOKEN_STRING, 29);
        to (58, TOKEN_STRKEY, 30);
        to (58, TOKEN_LBRACKET, 31);
        to (58, TOKEN_LBRACE, 32);
        to (58, value, 62);

        to (59, TOKEN_COMMA, 216);
        to (59, TOKEN_RBRACE, 216);

        to (60, TOKEN_LBRACKET, 246);
        to (60, TOKEN_ENDMARK, 246);
        to (60, TOKEN_BAREKEY, 8);
        to (60, TOKEN_STRKEY, 9);
        to (60, statements, 63);
        to (60, pair, 5);
        to (60, key, 7);

        to (61, TOKEN_LBRACKET, 243);
        to (61, TOKEN_ENDMARK, 243);
        to (61, TOKEN_BAREKEY, 8);
        to (61, TOKEN_STRKEY, 9);
        to (61, pair, 11);
        to (61, key, 7);

        to (62, TOKEN_COMMA, 222);
        to (62, TOKEN_RBRACKET, 222);
        to (62, TOKEN_ENDLINE, 41);
        to (62, endln, 64);

        to (63, TOKEN_LBRACKET, 247);
        to (63, TOKEN_ENDMARK, 247);
        to (63, TOKEN_BAREKEY, 8);
        to (63, TOKEN_STRKEY, 9);
        to (63, pair, 11);
        to (63, key, 7);

        to (64, TOKEN_COMMA, 223);
        to (64, TOKEN_RBRACKET, 223);

        nrhs.assign ({1, 2, 1, 1, 0, 6, 5, 8, 7, 5, 4, 7, 6, 3, 1, 1, 1, 3,
            2, 1, 1, 1, 1, 1, 1, 3, 3, 1, 1, 3, 3, 5, 0, 1, 0, 1, 2, 1, 3, 3});

        colgoto.assign ({
            start, toml, toml, toml, toml,
            sections, sections, sections, sections, sections, sections,
            sections, sections,
            keypath, keypath, key, key, statements, statements,
            value, value, value, value, value, value, value, value,
            array, array, array, value_list, value_list, endln, endln,
            table, table, table, pair_list, pair_list, pair});

    }
